Add base64
janet-lang/pkgs pull request #66
Opened 2024-06-23 18:31 UTC by Jakski

This is a pure Janet implementation of Base64. It's been added since there was an interest https://github.com/janet-lang/spork/pull/185

2024-06-24 02:40 UTC, sogaiu commented
Thanks for this!

2024-06-24 06:54 UTC, pepe requested changes
I am getting 404 on the url.

2024-06-24 08:24 UTC, Jakski commented
@pepe Thanks for verifying. I forgot to make it a public repository after preparing the code. It should be accessible now.

2024-06-25 08:43 UTC, pepe approved these changes
LGTM

2024-06-25 08:43 UTC, merged